name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      uses: actions/setup-node@v4
    - run: npm install
    - run: npm run bundle --if-present
    - run: |
        rm -rf dist;
        mv .next/standalone ./dist;
        mv .next/static ./dist/.next;
        cp README.md LICENSE ./dist
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ./dist
        compression-level: 9
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: Release.txt


